### PR TITLE
Bug #1276937- Values sidebar content 2 - What drives mozilla

### PR DESCRIPTION
**Pull request by FrancescoSTL**
I went ahead and built out the second values sidebar with your layout. 

A couple things to note: 
1. I added a `<br>` temporarily after each multiple choice item because they were attempting to be inline due to the short amount of text in the options (this is something I encountered in my previous values sidebar as well. It had to do with floating the radio button). Cmore mentioned that we should at least have a rough sketch for each sidebar for tomorrow, so I'll leave it with a linebreak for now and can edit the css later.
2. I changed the way that tokens were filling the list items, as the both began to leave the container for some reason. The new layout involves changing the background image of the list item itself rather than having an image within a list item. Although the javascript is a bit less clean, as you have to change one additional thing (the background url) for each sidebar, I think it works better overall. Let me know what you think about the style/code there and we can decide which version to adopt!

Ill shoot you over an email before the day ends so you have all of this in email instead of having to rummage through each PR.

### CODE REVIEW

**Comment by FrancescoSTL** [comment]
Todo for this branch:
1. Replace SVG icons that mternoway sent and send svgs through utility
2. Fix folder higherarchy
3. Replace titles
4. Add "default" to bottom of switch statements
5. Rebase with master

**Comment by schalkneethling** [comment]
This one still needs a rebase.

**Comment by FrancescoSTL** [comment]
Branch ready to merge.

**Comment by schalkneethling** [comment]
There is still some work required here but, to move this forward and get all the code up to the main Mozilla repo, I am merging these as is.

**Pull request merged**
