### PR TITLE
Bug #1276079 - Utility sidebar content 4 - Find your stuff (awesome-bar)

### PR DESCRIPTION
**Pull request by FrancescoSTL**
This should reflect the 4th sidebar in the utility path which highlights the awesome-bar.

### CODE REVIEW

**Comment by FrancescoSTL** [comment]
Todo for this branch:
1. Replace SVG icons that mternoway sent and send svgs through utility
2. Fix folder higherarchy
3. Replace titles
4. Add "default" to bottom of switch statements
5. Rebase with master

**Comment by schalkneethling** [comment]
This one still needs a rebase.

**Comment by FrancescoSTL** [comment]
Branch ready to merge.

**Comment by schalkneethling** [comment]
There is still some work required here but, to move this forward and get all the code up to the main Mozilla repo, I am merging these as is.

**Pull request merged**
