### PR TITLE
Bug #1274215 - Utility sidebar content 2 - Private Browsing

### PR DESCRIPTION
**Pull request by FrancescoSTL**
This should be the complete private browsing sidebar. Let me know if there is anything I should change!

### CODE REVIEW

**Comment by FrancescoSTL** [comment]
Todo for this branch:
1. Replace SVG icons that mternoway sent and send svgs through utility
2. Fix folder higherarchy
3. Replace titles
4. Add "default" to bottom of switch statements
5. Rebase with master

**Comment by FrancescoSTL** [comment]
Rebase complete for this branch. I'll note this in other branches as well, but it would be good if we could merge all this code and push to the other repo. This seems like a good stopping point since it is inbetween sprints.

Tasks to complete:
1. Uniform token implementation (fix tokens in one of the two versions we have)
2. Redesign of content 3 on utility track to match AMO
3. Replace titles w/ @chrismore suggested titles, or find a way to hide using CSS
4. Lint all JS files

**Comment by schalkneethling** [comment]
This one still needs a rebase.

**Comment by FrancescoSTL** [comment]
Branch ready to merge.

**Comment by schalkneethling** [comment]
There is still some work required here but, to move this forward and get all the code up to the main Mozilla repo, I am merging these as is.

**Pull request merged**
